### ISSUE TITLE
Multithreaded Port Range

### ISSUE THREAD

**Issue by wsteelenyc** [TudbuT/qft#9] opened 2023-02-22 22:12 UTC
If you made this multithreaded where it could transfer multiple packets at a time you could considerably increase transfer speed for large files.  This is how most of the accellerated file transfer application do it.

**Comment by TudbuT** [comment] 2023-02-23 19:07
I'm afraid I'd first need a fiber connection to be able to test that, because ATM my connection is the limiting factor. Getting a fiber connection would be very expensive and take a while, so it probably won't happen for now.

If anyone has a good connection and some coding knowledge, I'd love for someone to take on this issue.

**Comment by wsteelenyc** [comment] 2023-02-23 19:50
It's something I'd be willing to look at.  I coded a multithreaded udp file transfer solution many years ago.  I'll have to look at your code and then I may have some questions.  I did some things you probably aren't but you're also doing some useful things I never got around to.  Also. I've got a 1Gig fiber connection at my office and my home, so testing isn't an issue for me.  I've never done RUST programming before, but I've programmed in enough languages learning a new syntax and structure isn't that gig of a deal.

**Comment by TudbuT** [comment] 2023-02-23 20:31
I'd love your help!

> I'll have to look at your code and then I may have some questions. 

Sure, I'll gladly answer any questions. If I forget to look at this issue, you can reach me via email: qfti-mpr@mail.tudbut.de (the weird email address is so i can blacklist emails to it in case it gets picked up by spam bots, in which case ill update this message).

> I've never done RUST programming before, but I've programmed in enough languages learning a new syntax and structure isn't that gig of a deal.

https://youtu.be/br3GIIQeefY is a great resource.

**Comment by SupaGamer2017** [comment] 2023-02-23 23:43
> I'm afraid I'd first need a fiber connection to be able to test that, because ATM my connection is the limiting factor. Getting a fiber connection would be very expensive and take a while, so it probably won't happen for now.
> 
> If anyone has a good connection and some coding knowledge, I'd love for someone to take on this issue.

I know you kinda hate me, but I do have a wired fiber connection that can pull 300 Mbps reliably and I'd love to help the project out. I don't really have coding knowledge tho ._.

**Comment by TudbuT** [comment] 2023-02-24 20:58
> I know you kinda hate me, 

I don't, but I don't like talking to you that much. However this is a nonpersonal context so whatever.

> but I do have a wired fiber connection that can pull 300 Mbps reliably 

Wonderful!

> and I'd love to help the project out. I don't really have coding knowledge tho ._.

Thats makes this difficult as I'd have to remote into your PC for me to be able to test this efficiently, and thats just way too much of a hassle.

**Comment by zamu-flowerpot** [comment] 2023-03-23 12:11
Not to sound snarky, but couldn't you just test locally?

If you have gigabit LAN (which most home networks are), you could just test it within your LAN. Heck even running 2 VMs and have the helper run on the host should work as the loopback interface and virtio interfaces can hit multi-gigabit speeds.

Then when the design is sound, you can grab a VPS or two and test between them to measure the response on the internet.

**Comment by TudbuT** [comment] 2023-05-14 12:58
I don't have gigabit LAN, and most importantly, the main roadblock is ISP speeds. Most consumer ISPs have big limits set, and don't allow very much data to be transferred per packet, even tho they do allow many packets. The issue is that my internet connection is very slow to begin with, so I can't test anything with actual ISPs between the nodes.

**Comment by TudbuT** [comment] 2023-05-27 04:05
I think I will close this as WONTFIX for now, but I will keep it in the back of my mind and it will decently likely be added in a future update.

**Closed as completed by TudbuT** 2023-05-27 04:05 UTC
